name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    name: 'Build and Deploy'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Projects via NPM
      run: npm ci

    - name: Sync Repository to Remote
      uses: up9cloud/action-rsync@v1.3
      env:
        HOST: ${{ secrets.SYNC_SERVER }}
        PORT: ${{ secrets.SYNC_PORT }}
        USER: ${{ secrets.SYNC_USER }}
        KEY:  ${{ secrets.SYNC_SSH_PRIVATE_KEY }}
        TARGET: ${{ secrets.SYNC_TARGET_PATH }}
        ARGS_MORE: '--exclude=/node_modules/'
        SSH_ARGS: '-p ${{ secrets.SYNC_PORT }} -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=quiet'
        MODE: push
        RUN_SCRIPT_ON: source
