name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    name: 'Build and Deploy'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Projects via NPM
      run: npm ci

    - name: Sync Repository to Remote
      uses: up9cloud/action-rsync@v1.3
      env:
        HOST: ${{ secrets.SYNC_SERVER }}
        PORT: ${{ secrets.SYNC_PORT }}
        USER: ${{ secrets.SYNC_USER }}
        KEY:  ${{ secrets.SYNC_SSH_PRIVATE_KEY }}
        TARGET: ${{ secrets.SYNC_TARGET_PATH }}
        ARGS_MORE: '--exclude=/node_modules/'
        SSH_ARGS: '-p ${{ secrets.SYNC_PORT }} -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=quiet'
        MODE: push
        RUN_SCRIPT_ON: source
        VERBOSE: true
        
    - name: Remote Package Install via SSH
      uses: appleboy/ssh-action@v0.1.4
      env:
        NODE_VERSION: 12
        NODE_VENV_PATH: ~/nodevenv/node
      with:
        host: ${{ secrets.SYNC_SERVER }}
        port: ${{ secrets.SYNC_PORT }}
        username: ${{ secrets.SYNC_USER }}
        key: ${{ secrets.SYNC_SSH_PRIVATE_KEY }}
        script_stop: true
        envs: NODE_VERSION, NODE_VENV_PATH
        script: |
          NODE_MODULES_PATH=$NODE_VENV_PATH/$NODE_VERSION/lib
          NPM_PATH=$NODE_VENV_PATH/$NODE_VERSION/bin
          $NPM_PATH/npm install $NODE_MODULES_PATH

    - name: Remote Server Restart via SSH
      uses: appleboy/ssh-action@v0.1.4
      env:
        NODE_VERSION: 12
        NODE_VENV_PATH: ~/nodevenv/node
        CODE_PATH: ${{ secrets.SYNC_TARGET_PATH }}
        SELECTOR_PATH: /usr/sbin
      with:
        host: ${{ secrets.SYNC_SERVER }}
        port: ${{ secrets.SYNC_PORT }}
        username: ${{ secrets.SYNC_USER }}
        key: ${{ secrets.SYNC_SSH_PRIVATE_KEY }}
        script_stop: true
        envs: NODE_VERSION, NODE_VENV_PATH, CODE_PATH, SELECTOR_PATH
        script: |
          VENV_ACTIVATION_PATH=$NODE_VENV_PATH/$NODE_VERSION/bin
          source $VENV_ACTIVATION_PATH/activate && cd $CODE_PATH
          $SELECTOR_PATH/cloudlinux-selector restart --json --interpreter nodejs --app-root $CODE_PATH
