name: Build and Deploy via SFTP

on:
  push:
    branches: [ master ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    name: 'Build and Deploy'
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build --if-present
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@1.1
      with:
        username: ${{ secrets.SFTP_USERNAME }}
        server: ${{ secrets.SFTP_SERVER }}
        port: ${{ secrets.SFTP_PORT }}
        ssh_private_key: ${{ secrets.SFTP_PRIVATE_SSH_KEY }}
        remote_path: ${{ secrets.SFTP_REMOTE_PATH }}
        args: '-o ConnectTimeout=5'
